"""Modificar modelo NormalizedEEG

Revision ID: 0635b7847b5d
Revises: 128ece78d861
Create Date: 2024-03-31 13:17:41.476474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0635b7847b5d'
down_revision = '128ece78d861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consentimientos', schema=None) as batch_op:
        batch_op.alter_column('id_paciente',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('normalized_eeg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_psd', sa.JSON(), nullable=True))
        batch_op.drop_column('pointInterval')
        batch_op.drop_column('pointStart')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('normalized_eeg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pointStart', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('pointInterval', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('data_psd')

    with op.batch_alter_table('consentimientos', schema=None) as batch_op:
        batch_op.alter_column('id_paciente',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
