"""Modelos actualizados

Revision ID: 128ece78d861
Revises: 
Create Date: 2024-03-27 18:05:24.252989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '128ece78d861'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostico_previo',
    sa.Column('id_diagnostico_previo', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_diagnostico_previo')
    )
    op.create_table('historial_medico',
    sa.Column('id_historial_medico', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('historial_medico', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_historial_medico')
    )
    op.create_table('paciente_medicamento',
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_medicamento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_medicamento'], ['medicamentos.id_medicamento'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_paciente', 'id_medicamento')
    )
    op.drop_table('historiales_medicos')
    op.drop_table('pacientes_medicamentos')
    op.drop_table('diagnosticos_previos')
    with op.batch_alter_table('consentimientos', schema=None) as batch_op:
        batch_op.alter_column('id_paciente',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('logs_actividad_usuarios', schema=None) as batch_op:
        batch_op.alter_column('accion',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)

    with op.batch_alter_table('metricas_desempeno', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)

    with op.batch_alter_table('normalized_eeg', schema=None) as batch_op:
        batch_op.alter_column('id_sesion',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('raw_eeg', schema=None) as batch_op:
        batch_op.alter_column('id_sesion',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('resultados_prediccion', schema=None) as batch_op:
        batch_op.alter_column('resultado_prediccion',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)

    with op.batch_alter_table('sesiones', schema=None) as batch_op:
        batch_op.alter_column('id_paciente',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sesiones', schema=None) as batch_op:
        batch_op.alter_column('id_paciente',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('resultados_prediccion', schema=None) as batch_op:
        batch_op.alter_column('resultado_prediccion',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)

    with op.batch_alter_table('raw_eeg', schema=None) as batch_op:
        batch_op.alter_column('id_sesion',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('normalized_eeg', schema=None) as batch_op:
        batch_op.alter_column('id_sesion',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('metricas_desempeno', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)

    with op.batch_alter_table('logs_actividad_usuarios', schema=None) as batch_op:
        batch_op.alter_column('accion',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)

    with op.batch_alter_table('consentimientos', schema=None) as batch_op:
        batch_op.alter_column('id_paciente',
               existing_type=mysql.INTEGER(),
               nullable=True)

    op.create_table('diagnosticos_previos',
    sa.Column('id_diagnostico_previo', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('descripcion', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], name='diagnosticos_previos_ibfk_1'),
    sa.PrimaryKeyConstraint('id_diagnostico_previo'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pacientes_medicamentos',
    sa.Column('id_paciente', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_medicamento', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_medicamento'], ['medicamentos.id_medicamento'], name='pacientes_medicamentos_ibfk_2'),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], name='pacientes_medicamentos_ibfk_1'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('historiales_medicos',
    sa.Column('id_historial_medico', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('historial_medico', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], name='historiales_medicos_ibfk_1'),
    sa.PrimaryKeyConstraint('id_historial_medico'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('paciente_medicamento')
    op.drop_table('historial_medico')
    op.drop_table('diagnostico_previo')
    # ### end Alembic commands ###
