"""STFT

Revision ID: 62789d3d5872
Revises: 28dabd6b5176
Create Date: 2024-04-18 01:50:06.292621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62789d3d5872'
down_revision = '28dabd6b5176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('normalized_eeg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_stft', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('normalized_eeg', schema=None) as batch_op:
        batch_op.drop_column('data_stft')

    # ### end Alembic commands ###
