"""PSD and RP per Area-Band

Revision ID: 630e2a9810fa
Revises: 62789d3d5872
Create Date: 2024-04-30 15:11:20.047820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630e2a9810fa'
down_revision = '62789d3d5872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('normalized_eeg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_area_bandas_psd', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('data_area_bandas_pr', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('normalized_eeg', schema=None) as batch_op:
        batch_op.drop_column('data_area_bandas_pr')
        batch_op.drop_column('data_area_bandas_psd')

    # ### end Alembic commands ###
