"""Resultados Clasificaciones

Revision ID: a81603412509
Revises: ea3cecadf6fa
Create Date: 2024-05-16 01:43:42.053856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81603412509'
down_revision = 'ea3cecadf6fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('normalized_eeg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caracteristicas', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('normalized_eeg', schema=None) as batch_op:
        batch_op.drop_column('caracteristicas')

    # ### end Alembic commands ###
