"""Añadir columna data_areas a NormalizedEEG

Revision ID: abf0eb4ffe08
Revises: 1c8ab78ff006
Create Date: 2024-05-20 03:31:55.505318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf0eb4ffe08'
down_revision = '1c8ab78ff006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('normalized_eeg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_areas', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('normalized_eeg', schema=None) as batch_op:
        batch_op.drop_column('data_areas')

    # ### end Alembic commands ###
