"""Cambios UI

Revision ID: ea3cecadf6fa
Revises: 630e2a9810fa
Create Date: 2024-05-16 00:21:12.862669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3cecadf6fa'
down_revision = '630e2a9810fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactos_emergencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colonia', sa.String(length=255), nullable=True))

    with op.batch_alter_table('medicamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dosis', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicamentos', schema=None) as batch_op:
        batch_op.drop_column('dosis')

    with op.batch_alter_table('contactos_emergencia', schema=None) as batch_op:
        batch_op.drop_column('colonia')

    # ### end Alembic commands ###
