"""Añadir columna audio_consentimiento a Consentimiento

Revision ID: f8558af0ad52
Revises: 470d14dbecfa
Create Date: 2024-05-19 23:17:01.067351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8558af0ad52'
down_revision = '470d14dbecfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consentimientos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_consentimiento', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consentimientos', schema=None) as batch_op:
        batch_op.drop_column('audio_consentimiento')

    # ### end Alembic commands ###
